name: Neil Matouka
favicon: null
layout_spectrum: 0.00582229602150619
typography_spectrum: 0.29105259687639773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.287792936200276
  lightness: 0.6990139330737293
  saturation: 0.000929602887481451
  rhythmicContrast: 0.9243401840794832
purpose: []
