name: Neil Matouka
favicon: null
layout_spectrum: 0.24574
typography_spectrum: 0.28122
title: Neil Matouka
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.287792936200276
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
