typography_spectrum: 0.28122
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.287792936200276
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24574
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Neil Matouka
  email: neil@neilmatouka.com
  url: www.neilmatouka.com
name: Neil Matouka
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LinkedIn
    url: 'http://www.linkedin.com/in/neilmatouka'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/nmatouka'
    type: external
favicon: null
title: Neil Matouka
description: 'MEM, CGBP'
purpose: []
